apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-g3be
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0028-tenant/tkrw-pr712-0075-0028-app/devfile-sample-g3be@sha256:10fb8cb586df2e93e86e7ac21f07941a7872c835a2b1d594ac8c61011da1ea8f
        name: my-nodejs
        resources: {}
status: {}
